name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  CCACHE_ACTION_CI: true

jobs:
  build:
    # Run npm build and check that the dist/ folder is up to date.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          npm install
          git diff --exit-code

  test-large-build:
    strategy:
      matrix:
        evict: [true, false]

    runs-on: ubuntu-latest
    env:
      CMAKE_VERSION: 3.30.6
      CCACHE_SLOPPINESS: pch_defines,time_macros
    steps:
      - uses: actions/checkout@v4
      - name: Run ccache-action
        id: ccache
        uses: ./
        with:
          verbose: 2
          max-size: 1G
          key: evict-${{ matrix.evict }}
          evict-old-files: ${{ matrix.evict }}

      - name: download cmake sources
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz
          tar -xf cmake-${CMAKE_VERSION}.tar.gz

      - name: build cmake
        working-directory: cmake-${{ env.CMAKE_VERSION }}
        run: |
          cmake . -B build \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build build -j2
